### ISSUE TITLE
Not an issue, just a general question

### ISSUE THREAD

**Issue by llwt** [t3kt/vjzual4#40]
Hey @t3kt,

_Sorry for the random issue, github doesn't have a way to DM :)_

Does TD ship with the source for the internal python modules somewhere? I've been digging around trying to find them but haven't had much luck. 

I noticed you've got `vjzual4/lib/_stubs/TDJSON.py` and a few other files that look like they are based off of the original source. I was thinking about adding some unit tests into a project of mine for a few modules but was hoping to avoid mocking the world if possible.

**Comment by t3kt** [comment]
It does! If you jump to `/sys/TDModules` (or use `op.TDModules`), there are a bunch of DATs with libraries including TDFunctions and TDJSON. There are docs for them on the wiki.

You typically use them like this: `op.TDModules.mod.TDFunctions.parMenu(...)`

I just copied those out into separate files, solely for the purpose of being able to reference them in an IDE. So those files aren't actually used anywhere at runtime, they're just duplicates.

I also did a bunch of work manually writing out stubs for the built-in TD modules for things like `OP` and `Par` and so on. It's kind of tedious work but I've sort of automated some of it by parsing docs from the wiki semi-manually. I feel strongly about IDE support and static typing in Python. :P

I've taken up that practice for a while, so you'll see various projects of mine will have that same set of files, updated to whatever version of TD I was using when I last worked on the project. I pulled the most recent ones into [optexture/td-components](https://github.com/optexture/td-components).

I've periodically requested for Derivative to generate python type hint files based on their C++ implementations of those modules. But it's kind of an unusual thing to care about so..  ⋋| ◉ ͟ʖ ◉ |⋌

**Comment by llwt** [comment]
> I feel strongly about IDE support and static typing in Python

I share this same sentiment and it's been driving me crazy. I was surprised to not find anyone who'd run into the same issue until now.

 I've been sleuthing through your repos and have learned a bunch. Your work here is awesome and will save me a ton of time!

---

As an aside, is this or `td-rig` in active development? I was looking for a good way to compose together components/tox/glsl/etc. and didn't find anything. Simple mixer was kind of close but had a prescribed chain that wasn't flexible in the way I was looking so I started down the path of rolling my own (new to TD but been a SWE forever). 

Curious if you just use these internally? I noticed in `td-rig` things are called "chains" which piqued my interest :P

**Comment by t3kt** [comment]
`td-rig` is a setup for hosting and managing toxes that generate a video
output. Generally for me those are chains of my existing generator / effect
modules (see https://github.com/t3kt/vjzual4/tree/master/modules).
It's what I use when I want to make a thing that generates video but isn't
big enough to be a whole project.

There are two sides for the hosting infrastructure.
The editor system (rig.toe) is designed to host a single chain at a time
and has utilities for modifying them (adding parameters, etc), taking
snapshots of output, etc. This part works off the assumption that it's ok
to stall out briefly and reliability is less critical.

Then there's the runtime system (rig-runtime.toe). That one has a few
tracks into which chains are loaded. It the mixes those, switches between
them, routes midi to the selected chain, etc.  It's intended for use in
live performance, so reliability is super important.
The runtime part should be functional but I'm holding off on building it
out too much until external process tox hosting is stable enough to use.
Most of the components used in the runtime including the mixer parts are
from https://github.com/optexture/td-components.

... I should really post this stuff as documentation in those repos.. or
maybe posts on the derivative community board..

**Comment by llwt** [comment]
Ahh thanks, that connects all the dots for me!

Thanks again for making all this open source, it makes getting up to speed in this space much easier.
